//===- gpt2-main.cpp
//-------------------------------------------------------===//
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
//===----------------------------------------------------------------------===//
//
// Model-side driver for the Gpt2 (openai-community/gpt2) e2e workload.
//
// The signature below is the one emitted by import-gpt2.py into forward.mlir:
//
//   func.func @forward(%arg0: memref<124439808xf32>,  // packed float32 params
//                      %arg1: memref<1x9xi64>)        // input_ids
//     -> memref<1x9x50257xf32>                        // next-token logits
//
// Unlike llama2, the traced GPT-2 forward needs no int64 parameter buffer and
// no attention_mask (all-ones mask == causal-only for the unpadded fixed
// case), and buddy's Text container has no GPT-2 byte-level BPE tokenizer, so
// the workload's fixed prompt is embedded here as pre-tokenized ids that match
// pytorch-gpt2-lm.py. The complete logits tensor written to
// `gpt2_logits_f32.bin` is checked with
//
//   python3 pytorch-gpt2-lm.py --check <dir>/gpt2_logits_f32.bin
//
//===----------------------------------------------------------------------===//

#include <algorithm>
#include <buddy/Core/Container.h>
#include <chrono>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <numeric>
#include <string>
#include <vector>

namespace {

// Sizes of the AOT artifacts emitted by import-gpt2.py.
constexpr int64_t kFloat32Params = 124439808;
constexpr int64_t kSeqLen = 9;
constexpr int64_t kVocabSize = 50257;

// The workload's fixed case: "The quick brown fox jumps over the lazy dog"
// tokenized by the checkpoint's byte-level BPE without special tokens; must
// stay in sync with pytorch-gpt2-lm.py (INPUT_IDS).
const int64_t kInputIds[kSeqLen] = {464, 2068, 7586,  21831, 18045,
                                    625, 262,  16931, 3290};

void loadBinary(const std::string &path, char *dest, std::streamsize bytes) {
  std::ifstream file(path, std::ios::in | std::ios::binary);
  if (!file.is_open()) {
    std::string message = "Failed to open " + path;
    if (std::filesystem::exists(path))
      message += " (exists but unreadable)";
    throw std::runtime_error(message);
  }
  file.read(dest, bytes);
  if (!file)
    throw std::runtime_error("Failed to read the whole file: " + path);
}

/// Predict the top-k vocabulary ids for one token position.
std::vector<int64_t> topK(const float *row, int k) {
  std::vector<int64_t> ids(k);
  std::iota(ids.begin(), ids.end(), 0);
  std::sort(ids.begin(), ids.end(),
            [&](int64_t a, int64_t b) { return row[a] > row[b]; });
  ids.resize(k);
  return ids;
}

} // namespace

// Declare the GPT-2 forward function generated by the buddy frontend.
extern "C" void _mlir_ciface_forward(MemRef<float, 3> *result,
                                     MemRef<float, 1> *arg0,
                                     MemRef<long long, 2> *arg1);

int main(int argc, char **argv) {
  const std::string title = "GPT-2 Inference Powered by Buddy Compiler";
  std::cout << "\033[33;1m" << title << "\033[0m" << std::endl;

  // Directory holding arg0.data (import-gpt2.py output). Override with the
  // first CLI argument when running elsewhere.
  std::string modelDir = argc > 1 ? argv[1] : "./";
  if (!modelDir.empty() && modelDir.back() != '/')
    modelDir += '/';
  std::cout << "[Log] artifacts: " << modelDir << std::endl;

  /// Load the packed parameters into the MemRef container.
  MemRef<float, 1> params({kFloat32Params});
  loadBinary(modelDir + "arg0.data", reinterpret_cast<char *>(params.getData()),
             kFloat32Params * static_cast<int64_t>(sizeof(float)));
  std::cout << "[Log] loaded " << kFloat32Params << " float32 parameters"
            << std::endl;

  /// Feed the fixed pre-tokenized prompt (no C++ BPE tokenizer in buddy).
  MemRef<long long, 2> inputIds({1, kSeqLen}, false, 0);
  std::copy(std::begin(kInputIds), std::end(kInputIds), inputIds.getData());
  std::cout << "[Log] input: \""
            << "The quick brown fox jumps over the lazy dog\"" << std::endl;

  /// Execute forward inference of the model.
  MemRef<float, 3> logits({1, kSeqLen, kVocabSize});
  const auto inferenceStart = std::chrono::high_resolution_clock::now();
  _mlir_ciface_forward(&logits, &params, &inputIds);
  const auto inferenceEnd = std::chrono::high_resolution_clock::now();
  const std::chrono::duration<double, std::milli> inferenceTime =
      inferenceEnd - inferenceStart;

  /// Dump the *complete* output tensor so it can be compared element-wise with
  /// the canonical reference, not only with its argmax.
  const std::string outPath = modelDir + "gpt2_logits_f32.bin";
  {
    std::ofstream out(outPath,
                      std::ios::out | std::ios::binary | std::ios::trunc);
    out.write(reinterpret_cast<const char *>(logits.getData()),
              kSeqLen * kVocabSize * static_cast<int64_t>(sizeof(float)));
    if (!out)
      throw std::runtime_error("Failed to write " + outPath);
  }

  /// Report the per-position top-5 prediction ids of the LM head. Token-id
  /// strings live in reference/reference_manifest.json (BPE decode is out of
  /// scope for this container; see HANDOFF.md Known Limitation 3).
  const float *data = logits.getData();
  for (int64_t position = 0; position < kSeqLen; ++position) {
    std::cout << "[Result] pos " << position << ": ";
    for (int64_t id : topK(data + position * kVocabSize, 5))
      std::cout << id << " (" << data[position * kVocabSize + id] << ") ";
    std::cout << std::endl;
  }

  std::cout << "\033[33;1m[Time] \033[0m" << inferenceTime.count() << " ms"
            << std::endl;
  std::cout << "\033[33;1m[Log] \033[0mfull logits -> " << outPath << std::endl;
  return 0;
}
