#!/usr/bin/env bash
set -euo pipefail

ROOT=$(git rev-parse --show-toplevel)
BUDDY=${ROOT}/thirdparty/buddy-mlir
WITH_NV=0

while [ "${1:-}" != "" ]; do
  case $1 in
    --nv | --with-nv) WITH_NV=1 ;;
    -h | --help)
      echo "Usage: $0 [--nv]"
      exit 0 ;;
    *)
      echo "Error: invalid option $1" >&2
      exit 1 ;;
  esac
  shift
done

source ${ROOT}/scripts/utils.sh
source ${ROOT}/env.sh

pip install -r ${BUDDY}/requirements.txt
cd ${BUDDY}
git submodule update --init llvm

NV_CMAKE=()
if [ "${WITH_NV}" = "1" ]; then
  if [ -z "${CUDA_HOME:-}" ] || [ ! -x "${CUDA_HOME}/bin/nvcc" ]; then
    echo "ERROR: --nv requires CUDA_HOME with bin/nvcc (got CUDA_HOME=${CUDA_HOME:-unset})" >&2
    exit 1
  fi
  GXX13=$(command -v g++-13)
  if [ -z "${GXX13}" ]; then
    echo "ERROR: --nv requires g++-13 on PATH" >&2
    exit 1
  fi
  NV_CMAKE=(
    -DLLVM_TARGETS_TO_BUILD="host;RISCV;NVPTX"
    -DMLIR_ENABLE_CUDA_RUNNER=ON
    -DCMAKE_CUDA_COMPILER="${CUDA_HOME}/bin/nvcc"
    -DCUDAToolkit_ROOT="${CUDA_HOME}"
    -DCMAKE_CUDA_HOST_COMPILER="${GXX13}"
  )
else
  NV_CMAKE=(-DLLVM_TARGETS_TO_BUILD="host;RISCV")
fi

cmake -G Ninja -S llvm/llvm -B llvm/build \
  -DLLVM_ENABLE_PROJECTS="mlir;clang" \
  "${NV_CMAKE[@]}" \
  -DLLVM_ENABLE_ASSERTIONS=ON \
  -DCMAKE_BUILD_TYPE=RELEASE \
  -DMLIR_ENABLE_BINDINGS_PYTHON=ON \
  -DPython3_EXECUTABLE="$(which python3)"
ninja -C llvm/build

cmake -G Ninja -S . -B build \
  -DMLIR_DIR=$PWD/llvm/build/lib/cmake/mlir \
  -DLLVM_DIR=$PWD/llvm/build/lib/cmake/llvm \
  -DLLVM_ENABLE_ASSERTIONS=ON \
  -DCMAKE_BUILD_TYPE=RELEASE \
  -DBUDDY_MLIR_ENABLE_PYTHON_PACKAGES=ON \
  -DPython3_EXECUTABLE="$(which python3)" \
  -DPython_EXECUTABLE="$(which python3)"
ninja -C build

replace_content ${ROOT}/env.sh install-compiler "# line auto-generated by $0
export BUDDY_MLIR_BUILD_DIR=${BUDDY}/build
export LLVM_MLIR_BUILD_DIR=${BUDDY}/llvm/build
export PYTHONPATH=${BUDDY}/llvm/build/tools/mlir/python_packages/mlir_core:${BUDDY}/build/python_packages:\${PYTHONPATH}"

export BUDDY_MLIR_BUILD_DIR=${BUDDY}/build
export LLVM_MLIR_BUILD_DIR=${BUDDY}/llvm/build
export PYTHONPATH=${BUDDY}/llvm/build/tools/mlir/python_packages/mlir_core:${BUDDY}/build/python_packages:${PYTHONPATH:-}
